CREATE TABLE IF NOT EXISTS People(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fio varchar(100) NOT NULL,
    birthYear int NOT NULL
);

CREATE TABLE IF NOT EXISTS Books(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar(100) NOT NULL,
    releaseYear int NOT NULL,
    person_id int REFERENCES Person(id) ON DELETE SET NULL
);